development:
  adapter: postgresql
  database: bfyc89zturborzlgd8vo
  username: umnen5bgcwa7nhxwnjfy
  password: nGw4sU9zaLB7l4KozSeNR0DosmZdyL
  host: bfyc89zturborzlgd8vo-postgresql.services.clever-cloud.com
  port: 50013
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bfyc89zturborzlgd8vo
  username: umnen5bgcwa7nhxwnjfy
  password: nGw4sU9zaLB7l4KozSeNR0DosmZdyL
  host: bfyc89zturborzlgd8vo-postgresql.services.clever-cloud.com
  port: 50013
  pool: 5
  timeout: 5000

